begin;

do $test$
declare actor uuid; other_user uuid; challenge uuid; hash text; result jsonb; rejected boolean;
begin
 select id into actor from auth.users order by created_at desc limit 1;
 select id into other_user from auth.users where id<>actor order by created_at limit 1;
 assert actor is not null;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 assert not public.signup_phone_required(actor), 'Rollout disabled until endpoint ready';
 update public.signup_phone_policy set enforced_from=now()+interval '1 day';
 assert not public.signup_phone_required(actor), 'Existing accounts grandfathered';
 update public.signup_phone_policy set enforced_from='2000-01-01';
 assert public.signup_phone_required(actor), 'New signup needs verification';
 assert (public.signup_phone_status()->>'required')::boolean;
 hash:=encode(extensions.digest(actor::text||':+12025550123:123456','sha256'),'hex');
 challenge:=public.reserve_signup_phone_code(actor,'+12025550123',hash);
 result:=public.verify_signup_phone_code(null);
 assert not (result->>'ok')::boolean, 'Null code rejected';
 result:=public.verify_signup_phone_code('123456');
 assert not (result->>'ok')::boolean, 'Unsent challenge cannot verify';
 update public.signup_phone_challenges set delivery_state='sent' where id=challenge;
 result:=public.verify_signup_phone_code('000000');
 assert not (result->>'ok')::boolean;
 assert (select attempts from public.signup_phone_challenges where id=challenge)=1, 'Wrong attempt committed';
 rejected:=false;
 begin perform public.reserve_signup_phone_code(actor,'+12025550123',hash); exception when sqlstate 'P0001' then rejected:=true; end;
 assert rejected, 'Resend cooldown enforced';
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 result:=public.verify_signup_phone_code('123456');
 assert not (result->>'ok')::boolean, 'Code bound to account';
 perform set_config('request.jwt.claim.sub',actor::text,true);
 update public.signup_phone_challenges set attempts=5 where id=challenge;
 result:=public.verify_signup_phone_code('123456');
 assert not (result->>'ok')::boolean, 'Attempt limit enforced even for correct code';
 update public.signup_phone_challenges set attempts=1,expires_at=now()-interval '1 second' where id=challenge;
 result:=public.verify_signup_phone_code('123456');
 assert not (result->>'ok')::boolean, 'Expired code rejected';
 update public.signup_phone_challenges set expires_at=now()+interval '10 minutes' where id=challenge;
 result:=public.verify_signup_phone_code('123456');
 assert (result->>'ok')::boolean, 'Correct sent code accepted';
 assert not public.signup_phone_required(actor), 'Verified signup released';
 assert (select phone_e164 from public.signup_phone_verifications where user_id=actor)='+12025550123';
 result:=public.verify_signup_phone_code('123456');
 assert not (result->>'ok')::boolean, 'Used code cannot be replayed';
 assert not has_table_privilege('authenticated','public.signup_phone_verifications','INSERT'), 'No client proof writes';
 assert not has_table_privilege('authenticated','public.signup_phone_challenges','SELECT'), 'Hashes private';
 assert not has_function_privilege('authenticated','public.reserve_signup_phone_code(uuid,text,text)','EXECUTE'), 'Users cannot mint codes';
 assert not has_function_privilege('anon','public.verify_signup_phone_code(text)','EXECUTE'), 'Authentication required';
 assert position('NOT IN (''host'', ''shopper'')' in pg_get_functiondef('public.handle_new_user()'::regprocedure))>0,'Signup metadata cannot grant admin';
end $test$;
select 'PASS: mandatory verification, grandfathering, unsent/wrong/null/expired/replayed codes, attempt and resend limits, account binding, private proof and codes, signup role allowlist' result;
rollback;
