import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.2';
import { invokeTransactionalEmail } from '../_shared/invokeTransactionalEmail.ts';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});try{
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!); const token=req.headers.get('Authorization')?.replace('Bearer ',''); const {data:{user}}=await admin.auth.getUser(token||''); if(!user)return new Response('{}',{status:401,headers:cors});
 const {walkthrough_id,action}=await req.json(); const {data:w}=await admin.from('video_walkthroughs').select('*,listing:listings(title)').eq('id',walkthrough_id).maybeSingle(); if(!w||![w.buyer_id,w.seller_id].includes(user.id))return new Response('{}',{status:403,headers:cors});
 const recipient=user.id===w.buyer_id?w.seller_id:w.buyer_id, title=action==='cancelled'?'Video walkthrough cancelled':action==='rescheduled'?'Video walkthrough rescheduled':'Video walkthrough scheduled'; const when=new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeStyle:'short',timeZone:w.timezone_snapshot}).format(new Date(w.starts_at)); const message=`${w.listing?.title||'Listing'} · ${when} (${w.timezone_snapshot})`; const link=`/walkthrough/${w.id}`;
 const {data:n}=await admin.from('notifications').insert({user_id:recipient,type:`walkthrough_${action}`,title,message,link}).select().single(); const {data:p}=await admin.from('profiles').select('email,full_name').eq('id',recipient).maybeSingle();
 if(p?.email)await invokeTransactionalEmail({templateName:'generic-notice',recipientEmail:p.email,idempotencyKey:`walkthrough-${w.id}-${action}-${w.updated_at}`,templateData:{preview:title,kicker:'Video walkthrough',heading:title,greeting:`Hi ${p.full_name||'there'},`,paragraphs:[message],ctaLabel:'View walkthrough',ctaUrl:`${Deno.env.get('SITE_URL')||'https://vendibook.com'}${link}`,footnote:'Camera and microphone access are requested only when you join.'}});
 return new Response(JSON.stringify({success:true,notification_id:n?.id}),{headers:cors});
}catch(e){console.error('[video-walkthrough-notify]',e instanceof Error?e.message:'failed');return new Response(JSON.stringify({error:'notification_failed'}),{status:500,headers:cors});}});