import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CalendarPlus, Clock, Link2 as LinkIcon, MessageCircle, Video, XCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { downloadWalkthroughIcs, formatWalkthroughTime } from '@/lib/videoWalkthroughs';
import VendibookVideoCall from '@/components/video/VendibookVideoCall';
import WalkthroughConsentGate from '@/components/video/WalkthroughConsentGate';
import { toast } from 'sonner';

export default function WalkthroughDetail(){const {walkthroughId}=useParams();const {user,isLoading:loading}=useAuth();const navigate=useNavigate();const [search]=useSearchParams();const [w,setW]=useState<any>();const [stage,setStage]=useState<'none'|'gate'|'call'>('none');const load=()=>walkthroughId&&(supabase.from('video_walkthroughs') as any).select('*,listing:listings(title,cover_image_url,mode,host_id)').eq('id',walkthroughId).maybeSingle().then(({data}:any)=>setW(data));useEffect(()=>{load()},[walkthroughId]);if(!loading&&!user)return <Navigate to={`/auth?redirect=/walkthrough/${walkthroughId}`} replace/>;if(!w)return <main className="walkthrough-page"><div className="walkthrough-container walkthrough-loading">Loading walkthrough…</div></main>;
 const active=['scheduled','rescheduled'].includes(w.status),now=Date.now(),canJoin=active&&now>=+new Date(w.starts_at)-600000&&now<=+new Date(w.ends_at)+1800000;const cancel=async()=>{if(!confirm('Cancel this walkthrough? The other participant will be notified.'))return;const {error}=await (supabase.rpc as any)('cancel_video_walkthrough',{_walkthrough_id:w.id});if(error)return toast.error('Could not cancel.');await supabase.functions.invoke('video-walkthrough-notify',{body:{walkthrough_id:w.id,action:'cancelled'}});toast.success('Walkthrough cancelled.');load();};const handleLeave=async({joined}:{joined:boolean})=>{setStage('none');if(!joined){load();return;}try{await supabase.functions.invoke('video-walkthrough-exit',{body:{walkthrough_id:w.id}});}catch{/* exit record is best effort */}navigate(`/walkthrough/${w.id}/next-steps`,{replace:true});};if(stage==='gate')return <main className="walkthrough-page walkthrough-call-page"><div className="walkthrough-container"><WalkthroughConsentGate walkthroughId={w.id} title={w.listing?.title||'Video walkthrough'} requiresLocation={false} onReady={()=>setStage('call')} onCancel={()=>setStage('none')}/></div></main>;
 if(stage==='call')return <main className="walkthrough-page walkthrough-call-page"><VendibookVideoCall walkthroughId={w.id} title={w.listing?.title||'Video walkthrough'} onLeave={handleLeave}/></main>;
 return <main className="walkthrough-page"><header className="walkthrough-topbar"><Link to="/dashboard"><span>←</span> Dashboard</Link><Link to="/" className="walkthrough-brand">VENDIBOOK</Link></header><div className="walkthrough-container"><div className="walkthrough-heading"><p>{search.get('confirmed')?'You’re scheduled':'Walkthrough details'}</p><h1>{w.listing?.title}</h1><span>A private live video walkthrough inside Vendibook.</span></div><div className="walkthrough-detail-grid"><section className="walkthrough-card walkthrough-meeting-card">{w.listing?.cover_image_url&&<img src={w.listing.cover_image_url} alt=""/>}<div><span className={`v2-status ${active?'is-ok':'is-alert'}`}>{w.status}</span><h2>{formatWalkthroughTime(w.starts_at)}</h2><p><Clock/> {Math.round((+new Date(w.ends_at)-+new Date(w.starts_at))/60000)} minutes · {w.timezone_snapshot}</p></div></section><section className="walkthrough-card walkthrough-detail-actions"><h2>Meeting access</h2>{canJoin?<Button onClick={()=>setStage('gate')}><Video/>Join walkthrough</Button>:<p>{active?'Join opens 10 minutes before the scheduled start and closes 30 minutes after the meeting ends.':'This meeting is no longer active.'}</p>}{active&&<div className="walkthrough-roomlink"><span>Your meeting room link</span><code>{`${window.location.origin}/walkthrough/${w.id}`}</code><button onClick={()=>{navigator.clipboard?.writeText(`${window.location.origin}/walkthrough/${w.id}`).then(()=>toast.success('Meeting link copied.'),()=>toast.error('Could not copy the link.'));}}><LinkIcon/>Copy link</button><small>Same link for both of you. It only opens for the buyer and seller on this meeting.</small></div>}<div className="walkthrough-action-list"><button onClick={()=>downloadWalkthroughIcs(w)}><CalendarPlus/>Add to calendar</button>{w.conversation_id&&<Link to={`/dashboard/messages/${w.conversation_id}`}><MessageCircle/>Message</Link>}{active&&<><Link to={`/walkthrough/schedule/${w.listing_id}?reschedule=${w.id}`}><Clock/>Reschedule</Link><button onClick={cancel}><XCircle/>Cancel walkthrough</button></>}</div></section><section className="walkthrough-card walkthrough-topics-summary"><h2>What to cover</h2>{w.requested_topics?.length?<ul>{w.requested_topics.map((t:string)=><li key={t}>{t}</li>)}</ul>:<p>No specific topics requested.</p>}{w.buyer_note&&<blockquote>{w.buyer_note}</blockquote>}<p className="walkthrough-legal-links">Meetings may be monitored or recorded. You’ll accept the <Link to="/legal/video-walkthrough-terms">Walkthrough Terms of Use</Link> and <Link to="/legal/device-permissions-privacy">Privacy Notice</Link> before joining.</p><p className="walkthrough-legal-links">Keep your chat, offers and payments on Vendibook — it protects both of you from scams and gives us a record if there’s a dispute.</p></section></div></div></main>}