import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CalendarPlus, Clock, MessageCircle, Video, XCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { downloadWalkthroughIcs, formatWalkthroughTime } from '@/lib/videoWalkthroughs';
import VendibookVideoCall from '@/components/video/VendibookVideoCall';
import { toast } from 'sonner';

export default function WalkthroughDetail(){const {walkthroughId}=useParams();const {user,loading}=useAuth();const [search]=useSearchParams();const navigate=useNavigate();const [w,setW]=useState<any>();const [call,setCall]=useState(false);const load=()=>walkthroughId&&(supabase.from('video_walkthroughs') as any).select('*,listing:listings(title,cover_image_url,mode,host_id)').eq('id',walkthroughId).maybeSingle().then(({data}:any)=>setW(data));useEffect(()=>{load()},[walkthroughId]);if(!loading&&!user)return <Navigate to={`/auth?redirect=/walkthrough/${walkthroughId}`} replace/>;if(!w)return <main className="walkthrough-page"><div className="walkthrough-container walkthrough-loading">Loading walkthrough…</div></main>;
 const active=['scheduled','rescheduled'].includes(w.status),now=Date.now(),canJoin=active&&now>=+new Date(w.starts_at)-600000&&now<=+new Date(w.ends_at)+1800000;const cancel=async()=>{if(!confirm('Cancel this walkthrough? The other participant will be notified.'))return;const {error}=await (supabase.rpc as any)('cancel_video_walkthrough',{_walkthrough_id:w.id});if(error)return toast.error('Could not cancel.');await supabase.functions.invoke('video-walkthrough-notify',{body:{walkthrough_id:w.id,action:'cancelled'}});toast.success('Walkthrough cancelled.');load();};if(call)return <main className="walkthrough-page walkthrough-call-page"><VendibookVideoCall walkthroughId={w.id} title={w.listing?.title||'Video walkthrough'} onLeave={()=>setCall(false)}/></main>;
 return <main className="walkthrough-page"><header className="walkthrough-topbar"><Link to="/dashboard"><span>←</span> Dashboard</Link><Link to="/" className="walkthrough-brand">VENDIBOOK</Link></header><div className="walkthrough-container"><div className="walkthrough-heading"><p>{search.get('confirmed')?'You’re scheduled':'Walkthrough details'}</p><h1>{w.listing?.title}</h1><span>A private live video walkthrough inside Vendibook.</span></div><div className="walkthrough-detail-grid"><section className="walkthrough-card walkthrough-meeting-card">{w.listing?.cover_image_url&&<img src={w.listing.cover_image_url} alt=""/>}<div><span className={`v2-status ${active?'is-ok':'is-alert'}`}>{w.status}</span><h2>{formatWalkthroughTime(w.starts_at)}</h2><p><Clock/> {Math.round((+new Date(w.ends_at)-+new Date(w.starts_at))/60000)} minutes · {w.timezone_snapshot}</p></div></section><section className="walkthrough-card walkthrough-detail-actions"><h2>Meeting access</h2>{canJoin?<Button onClick={()=>setCall(true)}><Video/>Join walkthrough</Button>:<p>{active?'Join opens 10 minutes before the scheduled start and closes 30 minutes after the meeting ends.':'This meeting is no longer active.'}</p>}<div className="walkthrough-action-list"><button onClick={()=>downloadWalkthroughIcs(w)}><CalendarPlus/>Add to calendar</button>{w.conversation_id&&<Link to={`/dashboard/messages/${w.conversation_id}`}><MessageCircle/>Message</Link>}{active&&<><Link to={`/walkthrough/schedule/${w.listing_id}?reschedule=${w.id}`}><Clock/>Reschedule</Link><button onClick={cancel}><XCircle/>Cancel walkthrough</button></>}</div></section><section className="walkthrough-card walkthrough-topics-summary"><h2>What to cover</h2>{w.requested_topics?.length?<ul>{w.requested_topics.map((t:string)=><li key={t}>{t}</li>)}</ul>:<p>No specific topics requested.</p>}{w.buyer_note&&<blockquote>{w.buyer_note}</blockquote>}</section><section className="walkthrough-card"><h2>Privacy</h2><p>Only the scheduled buyer and seller can access this call. Recording and transcription are off.</p></section></div></div></main>}