import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, CalendarDays, Check, Clock, Loader2, MapPin, Video } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { WALKTHROUGH_TOPICS, formatWalkthroughTime } from '@/lib/videoWalkthroughs';
import { trackEventToDb } from '@/hooks/useAnalyticsEvents';
import { toast } from 'sonner';

type Slot={starts_at:string;ends_at:string;seller_timezone:string};
export default function WalkthroughSchedule(){
 const {listingId}=useParams(); const [search]=useSearchParams(); const navigate=useNavigate(); const {user,isLoading:authLoading}=useAuth(); const rescheduleId=search.get('reschedule');
 const [listing,setListing]=useState<any>(); const [slots,setSlots]=useState<Slot[]>([]); const [selected,setSelected]=useState(''); const [topics,setTopics]=useState<string[]>([]); const [note,setNote]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!user||!listingId)return; trackEventToDb('walkthrough_scheduling_started','video_walkthrough',{},listingId); const from=new Date(),to=new Date(Date.now()+31*864e5); Promise.all([(supabase.from('listings') as any).select('id,title,cover_image_url,city,state,host_id').eq('id',listingId).maybeSingle(),(supabase.rpc as any)('get_video_walkthrough_slots',{_listing_id:listingId,_from:from.toISOString(),_to:to.toISOString()})]).then(async([l,s])=>{let row=l.data;if(row?.host_id){const {data:host}=await (supabase.rpc as any)('get_safe_host_profile',{host_user_id:row.host_id});row={...row,host:Array.isArray(host)?host[0]:host};}setListing(row);setSlots(s.data||[]);setLoading(false);});},[user,listingId]);
  const days=useMemo(()=>Object.entries(slots.reduce((a:Record<string,Slot[]>,s)=>{const k=new Date(s.starts_at).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});(a[k]||=[]).push(s);return a;},{})),[slots]);
 useEffect(()=>{if(days.length&&!days.some(([d])=>d===activeDay))setActiveDay(days[0][0]);},[days,activeDay]);
 if(!authLoading&&!user)return <Navigate to={`/auth?redirect=${encodeURIComponent(location.pathname+location.search)}`} replace/>;
 const schedule=async()=>{if(!listingId||!selected)return;setSaving(true);const {data,error}=rescheduleId?await (supabase.rpc as any)('reschedule_video_walkthrough',{_walkthrough_id:rescheduleId,_starts_at:selected}):await (supabase.rpc as any)('create_video_walkthrough',{_listing_id:listingId,_starts_at:selected,_conversation_id:search.get('conversation')||null,_requested_topics:topics,_buyer_note:note});if(error){toast.error(error.message.includes('slot_unavailable')?'That time was just booked. Choose another slot.':'Could not schedule this time.');setSaving(false);return;}const action=rescheduleId?'rescheduled':'scheduled';await supabase.functions.invoke('video-walkthrough-notify',{body:{walkthrough_id:data.id,action}});trackEventToDb(`walkthrough_${action}`,'video_walkthrough',{walkthrough_id:data.id},listingId);navigate(`/walkthrough/${data.id}?confirmed=1`);};
 return <main className="walkthrough-page"><header className="walkthrough-topbar"><Link to={listingId?`/listing/${listingId}`:'/dashboard'}><ArrowLeft/> Back</Link><Link to="/" className="walkthrough-brand">VENDIBOOK</Link></header><div className="walkthrough-container">
  <div className="walkthrough-heading"><p>Private 1:1 meeting</p><h1>{rescheduleId?'Reschedule':'Schedule'} a video walkthrough</h1><span>See this truck or trailer live before you travel.</span></div>
  {loading?<div className="walkthrough-card walkthrough-loading"><Loader2 className="animate-spin"/></div>:!listing?<div className="walkthrough-card">This listing is unavailable.</div>:<div className="walkthrough-schedule-grid"><section className="walkthrough-card walkthrough-listing-context">{listing.cover_image_url&&<img src={listing.cover_image_url} alt=""/>}<div><span className="walkthrough-kicker">Live video walkthrough</span><h2>{listing.title}</h2><p><MapPin/> {[listing.city,listing.state].filter(Boolean).join(', ')}</p><p>With {listing.host?.business_name||listing.host?.display_name||listing.host?.full_name||'the seller'} {listing.host?.identity_verified&&<span className="v2-status is-ok">Verified</span>}</p></div></section>
  <section className="walkthrough-card walkthrough-form"><div><span className="walkthrough-step">01</span><h2>What would you like to see?</h2><p>Select anything useful. This helps the seller prepare.</p><div className="walkthrough-topics">{WALKTHROUGH_TOPICS.map(t=><button key={t} className={topics.includes(t)?'is-selected':''} onClick={()=>setTopics(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])}>{topics.includes(t)&&<Check/>}{t}</button>)}</div></div>
  <div><span className="walkthrough-step">02</span><h2>Choose a time</h2><p>Only the days and times this seller is actually available are listed. Dates they have blocked off are not shown. Times are in your local timezone; the seller is in {slots[0]?.seller_timezone||'their own timezone'}.</p>{days.length?<><div className="walkthrough-daypicker">{days.map(([day,items])=><button key={day} className={activeDay===day?'is-selected':''} onClick={()=>setActiveDay(day)}><strong>{day}</strong><small>{items.length} time{items.length===1?'':'s'}</small></button>)}</div><div className="walkthrough-timegrid">{(days.find(([d])=>d===activeDay)?.[1]||[]).map(slot=><button className={selected===slot.starts_at?'is-selected':''} key={slot.starts_at} onClick={()=>setSelected(slot.starts_at)}>{new Date(slot.starts_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</button>)}</div></>:<p className="walkthrough-unavailable">This seller has no open walkthrough times in the next 31 days. Message them to coordinate.</p>}</div>
  <div><span className="walkthrough-step">03</span><h2>Add a note</h2><Textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="I’d like to see the fryer setup and generator running."/></div>
  <div className="walkthrough-confirm"><div><CalendarDays/><span><strong>{selected?formatWalkthroughTime(selected):'Select an available time'}</strong><small>{selected?`${Math.round((+new Date(slots.find(s=>s.starts_at===selected)!.ends_at)-+new Date(selected))/60000)} minute walkthrough`:'You will confirm before scheduling.'}</small></span></div><Button onClick={schedule} disabled={!selected||saving}>{saving?<Loader2 className="animate-spin"/>:<Video/>}Confirm walkthrough</Button></div></section></div>}
 </div></main>;
}