import { useEffect, useRef, useState } from 'react';
import DailyIframe, { type DailyCall } from '@daily-co/daily-js';
import { Camera, CameraOff, Loader2, Mic, MicOff, PhoneOff, RefreshCw } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';

export default function VendibookVideoCall({walkthroughId,title,onLeave}:{walkthroughId:string;title:string;onLeave:()=>void}){
 const frame=useRef<HTMLDivElement>(null),call=useRef<DailyCall|null>(null); const [phase,setPhase]=useState<'preview'|'joining'|'joined'|'error'>('preview'); const [error,setError]=useState(''); const [mic,setMic]=useState(true),[cam,setCam]=useState(true),[devices,setDevices]=useState<MediaDeviceInfo[]>([]); const [camera,setCamera]=useState(''),[microphone,setMicrophone]=useState('');
 useEffect(()=>{navigator.mediaDevices?.getUserMedia({video:true,audio:true}).then(stream=>{stream.getTracks().forEach(t=>t.stop());return navigator.mediaDevices.enumerateDevices();}).then(setDevices).catch(()=>setError('Camera or microphone permission is blocked. You can update browser permissions and try again.'));return()=>{call.current?.destroy();};},[]);
 const join=async()=>{setPhase('joining');const {data,error:e}=await supabase.functions.invoke('video-walkthrough-access',{body:{walkthrough_id:walkthroughId}});if(e||!data?.token){setError(data?.message||'Native video is unavailable. Your scheduled walkthrough remains saved.');setPhase('error');return;} try{const c=DailyIframe.createCallObject({videoSource:camera||true,audioSource:microphone||true});call.current=c;c.on('joined-meeting',()=>setPhase('joined')).on('left-meeting',onLeave).on('error',ev=>{setError(ev?.errorMsg||'The call was interrupted.');setPhase('error');});await c.join({url:data.roomUrl,token:data.token});}catch(err){setError(err instanceof Error?err.message:'Could not join.');setPhase('error');}};
 useEffect(()=>{if(phase!=='joined'||!frame.current||!call.current)return;const paint=()=>{const participants=call.current!.participants();frame.current!.innerHTML='';Object.values(participants).forEach((p:any)=>{const track=p.tracks?.video?.persistentTrack;if(!track)return;const v=document.createElement('video');v.autoplay=true;v.playsInline=true;v.muted=p.local;v.srcObject=new MediaStream([track]);v.className=p.local?'walkthrough-self-video':'walkthrough-remote-video';frame.current!.appendChild(v);});};call.current.on('participant-joined',paint).on('participant-updated',paint);paint();return()=>{call.current?.off('participant-joined',paint).off('participant-updated',paint);};},[phase]);
 const toggleMic=()=>{const v=!mic;setMic(v);call.current?.setLocalAudio(v)};const toggleCam=()=>{const v=!cam;setCam(v);call.current?.setLocalVideo(v)};const flip=async()=>{const cams=devices.filter(d=>d.kind==='videoinput');if(cams.length<2)return;const i=cams.findIndex(d=>d.deviceId===(call.current as any)?.getInputDevices?.().camera?.deviceId);await call.current?.setInputDevicesAsync({videoDeviceId:cams[(i+1)%cams.length].deviceId});};
 if(phase!=='joined')return <div className="walkthrough-prejoin"><div className="walkthrough-preview"><Camera/><span>{cam?'Camera preview will appear when you join':'Camera is off'}</span></div><h2>Ready for your walkthrough?</h2><p>{title}</p>{error&&<div className="walkthrough-error">{error}</div>}<div className="walkthrough-device-grid"><label>Camera<select value={camera} onChange={e=>setCamera(e.target.value)}><option value="">Default camera</option>{devices.filter(d=>d.kind==='videoinput').map(d=><option value={d.deviceId}>{d.label||'Camera'}</option>)}</select></label><label>Microphone<select value={microphone} onChange={e=>setMicrophone(e.target.value)}><option value="">Default microphone</option>{devices.filter(d=>d.kind==='audioinput').map(d=><option value={d.deviceId}>{d.label||'Microphone'}</option>)}</select></label></div><div className="walkthrough-prejoin-actions"><Button variant="outline" onClick={()=>setMic(!mic)}>{mic?<Mic/>:<MicOff/>}</Button><Button variant="outline" onClick={()=>setCam(!cam)}>{cam?<Camera/>:<CameraOff/>}</Button><Button onClick={join} disabled={phase==='joining'}>{phase==='joining'?<Loader2 className="animate-spin"/>:<Camera/>}Join walkthrough</Button></div></div>;
 return <div className="walkthrough-call"><div className="walkthrough-call-head"><strong>{title}</strong><span>Vendibook private walkthrough</span></div><div className="walkthrough-video-stage" ref={frame}><p>Waiting for the other participant to join.</p></div><div className="walkthrough-call-controls"><button onClick={toggleMic}>{mic?<Mic/>:<MicOff/>}<span>{mic?'Mute':'Unmute'}</span></button><button onClick={toggleCam}>{cam?<Camera/>:<CameraOff/>}<span>{cam?'Camera off':'Camera on'}</span></button><button className="walkthrough-flip" onClick={flip}><RefreshCw/><span>Flip camera</span></button><button className="is-leave" onClick={()=>call.current?.leave()}><PhoneOff/><span>Leave</span></button></div></div>;
}