// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-listings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var SUPABASE_URL = process.env.SUPABASE_URL;
var SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search Vendibook listings",
  description: "Search published Vendibook marketplace listings (food trucks, trailers, shared kitchens, vendor lots) by keyword, city, or transaction type. Returns public listing summaries only.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search across title and description."),
    city: z.string().optional().describe("Filter by city name."),
    transaction_type: z.enum(["rent", "sale", "any"]).optional().describe("Filter by rent, sale, or any."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, transaction_type, limit }) => {
    const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("listings").select("id,title,city,state,price,transaction_type,category,published_at").eq("status", "published").not("published_at", "is", null).is("deleted_at", null).eq("moderation_status", "clear").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (query) q = q.ilike("title", `%${query}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    if (transaction_type && transaction_type !== "any") {
      q = q.eq("transaction_type", transaction_type);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SUPABASE_URL2 = process.env.SUPABASE_URL;
var SUPABASE_KEY2 = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "Get a Vendibook listing",
  description: "Fetch the full public detail for a single published Vendibook listing by id.",
  inputSchema: {
    listing_id: z2.string().uuid().describe("The listing UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ listing_id }) => {
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_KEY2, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("listings").select("*").eq("id", listing_id).eq("status", "published").not("published_at", "is", null).is("deleted_at", null).eq("moderation_status", "clear").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Listing not found or not published." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { listing: data }
    };
  }
});

// src/lib/mcp/tools/list-my-listings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SUPABASE_URL3 = process.env.SUPABASE_URL;
var SUPABASE_KEY3 = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
function supabaseForUser(ctx) {
  return createClient3(SUPABASE_URL3, SUPABASE_KEY3, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_listings_default = defineTool3({
  name: "list_my_listings",
  title: "List my Vendibook listings",
  description: "List all listings owned by the signed-in Vendibook user (drafts, published, and archived).",
  inputSchema: {
    status: z3.enum(["draft", "published", "archived", "any"]).optional().describe("Filter by status, default any."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    let q = supabaseForUser(ctx).from("listings").select("id,title,status,transaction_type,city,state,price,published_at,updated_at").eq("owner_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status && status !== "any") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var SUPABASE_URL4 = process.env.SUPABASE_URL;
var SUPABASE_KEY4 = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
function supabaseForUser2(ctx) {
  return createClient4(SUPABASE_URL4, SUPABASE_KEY4, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_bookings_default = defineTool4({
  name: "list_my_bookings",
  title: "List my Vendibook bookings",
  description: "List bookings made by the signed-in Vendibook user, most recent first. Respects Vendibook's per-user access rules.",
  inputSchema: {
    role: z4.enum(["shopper", "host", "any"]).optional().describe("Filter by whether you are the shopper (renter/buyer) or the host. Default any."),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ role, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const uid = ctx.getUserId();
    let q = supabaseForUser2(ctx).from("bookings").select(
      "id,listing_id,status,payment_status,start_date,end_date,total_amount,shopper_id,host_id,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (role === "shopper") q = q.eq("shopper_id", uid);
    else if (role === "host") q = q.eq("host_id", uid);
    else q = q.or(`shopper_id.eq.${uid},host_id.eq.${uid}`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/check-listing-blockers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser3(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient5(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/check-listing-blockers.ts
import { getStageRequirements } from "npm:@/lib/listings/stages";
var check_listing_blockers_default = defineTool5({
  name: "check_listing_blockers",
  title: "Check listing publish blockers",
  description: "Return the remaining blockers that prevent a Vendibook listing from being published. The caller must own the listing.",
  inputSchema: {
    listing_id: z5.string().uuid().describe("The listing UUID to inspect.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ listing_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const uid = ctx.getUserId();
    const { data: row, error } = await supabase.from("listings").select(
      "id, host_id, status, title, description, category, mode, city, state, price_sale, price_monthly, price_weekly, price_daily, price_hourly, image_urls, condition, operational_status, title_status, has_lien, no_known_problems, known_problems, included_items, length_inches, height_inches, photos_exclusions_answered, published_at, deleted_at, moderation_status"
    ).eq("id", listing_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!row) {
      return { content: [{ type: "text", text: "Listing not found." }], isError: true };
    }
    const listing = row;
    if (listing.host_id !== uid) {
      return { content: [{ type: "text", text: "You do not own this listing." }], isError: true };
    }
    if (listing.deleted_at) {
      return { content: [{ type: "text", text: "This listing has been deleted." }], isError: true };
    }
    const blockers = [];
    if (!listing.title) blockers.push("Add a headline/title.");
    if (!listing.description) blockers.push("Add a description.");
    if (!listing.category) blockers.push("Select a category (food truck, trailer, etc.).");
    if (!listing.mode) blockers.push("Select whether this is for sale or rent.");
    if (!listing.city || !listing.state) blockers.push("Set the city and state location.");
    const images = Array.isArray(listing.image_urls) ? listing.image_urls : [];
    if (!images.length) blockers.push("Upload at least one photo.");
    const mode = listing.mode;
    if (mode === "sale") {
      if (Number(listing.price_sale) <= 0) blockers.push("Set the sale price.");
    } else if (mode === "rent") {
      const hasRate = Number(listing.price_monthly) > 0 || Number(listing.price_weekly) > 0 || Number(listing.price_daily) > 0 || Number(listing.price_hourly) > 0;
      if (!hasRate) blockers.push("Set at least one rental rate (monthly, weekly, daily, or hourly).");
    } else {
      blockers.push("Set whether the listing is for sale or rent so pricing can be checked.");
    }
    if (mode && listing.category) {
      try {
        const stageReqs = getStageRequirements({
          mode,
          category: listing.category,
          condition: listing.condition ?? null,
          operationalStatus: listing.operational_status ?? null,
          titleStatus: listing.title_status ?? null,
          hasLien: listing.has_lien ?? null,
          noKnownProblems: Boolean(listing.no_known_problems),
          knownProblems: Array.isArray(listing.known_problems) ? listing.known_problems : [],
          includedItems: listing.included_items ?? null,
          photosExclusionsAnswered: Boolean(listing.photos_exclusions_answered),
          lengthInches: listing.length_inches ?? null,
          heightInches: listing.height_inches ?? null
        });
        for (const req of stageReqs) {
          blockers.push(req.label);
        }
      } catch {
      }
    }
    const isPublished = listing.status === "published" && listing.published_at;
    const moderation = listing.moderation_status;
    if (moderation && moderation !== "clear") {
      blockers.push("This listing is under review by our team and cannot be published right now.");
    }
    return {
      content: [
        {
          type: "text",
          text: blockers.length === 0 ? isPublished ? "This listing is already published and live." : "No blockers \u2014 the listing is ready to publish." : `Blockers (${blockers.length}): ${blockers.join("; ")}`
        }
      ],
      structuredContent: {
        listing_id,
        ready: blockers.length === 0 && !isPublished,
        already_published: Boolean(isPublished),
        blockers
      }
    };
  }
});

// src/lib/mcp/tools/publish-listing.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
import { getStageRequirements as getStageRequirements2 } from "npm:@/lib/listings/stages";
var BLOCKED_STATUSES = /* @__PURE__ */ new Set([
  "removed",
  "deleted",
  "rejected",
  "suspended",
  "sold",
  "rented"
]);
var publish_listing_default = defineTool6({
  name: "publish_listing",
  title: "Publish a Vendibook listing",
  description: "Publish a Vendibook listing owned by the signed-in user. Requires all blockers to be cleared and a legal acknowledgment. The caller must have already recorded the typed YES consent in the app; this tool verifies it was recorded before publishing.",
  inputSchema: {
    listing_id: z6.string().uuid().describe("The listing UUID to publish."),
    consent_acknowledged: z6.boolean().describe("Must be true. The tool verifies the seller's typed YES consent is recorded server-side.").default(false)
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ listing_id, consent_acknowledged }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    if (!consent_acknowledged) {
      return {
        content: [{ type: "text", text: "You must acknowledge the seller disclosure and type YES on screen before publishing." }],
        isError: true
      };
    }
    const supabase = supabaseForUser3(ctx);
    const uid = ctx.getUserId();
    const { data: current, error: readError } = await supabase.from("listings").select(
      "id, host_id, status, published_at, deleted_at, moderation_status, title, description, category, mode, city, state, price_sale, price_monthly, price_weekly, price_daily, price_hourly, image_urls, condition, operational_status, title_status, has_lien, no_known_problems, known_problems, included_items, length_inches, height_inches, photos_exclusions_answered, seller_disclosure_acknowledged"
    ).eq("id", listing_id).maybeSingle();
    if (readError) {
      return { content: [{ type: "text", text: `Read failed: ${readError.message}` }], isError: true };
    }
    if (!current) {
      return { content: [{ type: "text", text: "Listing not found." }], isError: true };
    }
    const listing = current;
    if (listing.host_id !== uid) {
      return { content: [{ type: "text", text: "You do not own this listing." }], isError: true };
    }
    const moderation = listing.moderation_status;
    if (listing.deleted_at || BLOCKED_STATUSES.has(String(listing.status)) || moderation && moderation !== "clear") {
      return {
        content: [{ type: "text", text: "This listing cannot be published right now. It may be under review, sold, rented, or removed." }],
        isError: true
      };
    }
    if (listing.status === "published" && listing.published_at) {
      return {
        content: [{ type: "text", text: "This listing is already published." }],
        structuredContent: { listing_id, public_url: `/listing/${listing_id}`, already_published: true }
      };
    }
    if (!listing.seller_disclosure_acknowledged) {
      return {
        content: [
          {
            type: "text",
            text: "The seller disclosure has not been acknowledged. The seller must read the disclosure and type YES on screen before publishing."
          }
        ],
        isError: true
      };
    }
    const blockers = [];
    if (!listing.title) blockers.push("Add a headline/title.");
    if (!listing.description) blockers.push("Add a description.");
    if (!listing.category) blockers.push("Select a category.");
    if (!listing.mode) blockers.push("Select sale or rent.");
    if (!listing.city || !listing.state) blockers.push("Set city and state.");
    const images = Array.isArray(listing.image_urls) ? listing.image_urls : [];
    if (!images.length) blockers.push("Upload at least one photo.");
    const mode = listing.mode;
    if (mode === "sale") {
      if (Number(listing.price_sale) <= 0) blockers.push("Set the sale price.");
    } else if (mode === "rent") {
      const hasRate = Number(listing.price_monthly) > 0 || Number(listing.price_weekly) > 0 || Number(listing.price_daily) > 0 || Number(listing.price_hourly) > 0;
      if (!hasRate) blockers.push("Set at least one rental rate.");
    } else {
      blockers.push("Set sale or rent.");
    }
    if (mode && listing.category) {
      try {
        const stageReqs = getStageRequirements2({
          mode,
          category: listing.category,
          condition: listing.condition ?? null,
          operationalStatus: listing.operational_status ?? null,
          titleStatus: listing.title_status ?? null,
          hasLien: listing.has_lien ?? null,
          noKnownProblems: Boolean(listing.no_known_problems),
          knownProblems: Array.isArray(listing.known_problems) ? listing.known_problems : [],
          includedItems: listing.included_items ?? null,
          photosExclusionsAnswered: Boolean(listing.photos_exclusions_answered),
          lengthInches: listing.length_inches ?? null,
          heightInches: listing.height_inches ?? null
        });
        for (const req of stageReqs) blockers.push(req.label);
      } catch {
      }
    }
    if (blockers.length) {
      return {
        content: [{ type: "text", text: `Cannot publish yet. ${blockers.join("; ")}` }],
        structuredContent: { listing_id, blockers },
        isError: true
      };
    }
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { data: claimed, error: claimError } = await supabase.from("listings").update({ status: "published", published_at: nowIso }).eq("id", listing_id).is("published_at", null).select("published_at");
    if (claimError) {
      return { content: [{ type: "text", text: `Publish failed: ${claimError.message}` }], isError: true };
    }
    if (!claimed || claimed.length === 0) {
      const { data: rows, error: updateError } = await supabase.from("listings").update({ status: "published" }).eq("id", listing_id).select("published_at");
      if (updateError) {
        return { content: [{ type: "text", text: `Publish failed: ${updateError.message}` }], isError: true };
      }
      if (!rows || rows.length === 0) {
        return {
          content: [{ type: "text", text: "Publishing did not complete. Your draft is safe \u2014 please try again." }],
          isError: true
        };
      }
    }
    const { data: verified, error: verifyError } = await supabase.from("listings").select("status, published_at").eq("id", listing_id).maybeSingle();
    if (verifyError || !verified || verified.status !== "published" || !verified.published_at) {
      return {
        content: [{ type: "text", text: "Publishing did not complete. Your listing is still a draft \u2014 please try again." }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Published! Your listing is live at /listing/${listing_id}.`
        }
      ],
      structuredContent: {
        listing_id,
        public_url: `/listing/${listing_id}`,
        published_at: verified.published_at
      }
    };
  }
});

// src/lib/mcp/tools/list-upsell-products.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var list_upsell_products_default = defineTool7({
  name: "list_upsell_products",
  title: "List Vendibook upgrade products",
  description: "Return the Vendibook upsell products available to the signed-in user, such as Vendibook Pro membership, Featured Boost, Listing Concierge, and buyer financing/freight options. Prices come from the live catalog.",
  inputSchema: {
    listing_id: z7.string().uuid().optional().describe("Optional listing UUID to scope upgrades to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ listing_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("monetization_products").select("id, slug, name, description, billing_type, price_cents, promo_price_cents, promo_starts_at, promo_ends_at, duration_days, is_active").eq("is_active", true).in("slug", [
      "vendibook_pro",
      "boost-featured-30",
      "pro_listing_30",
      "listing_concierge"
    ]).order("display_order");
    if (error) {
      return { content: [{ type: "text", text: `Catalog lookup failed: ${error.message}` }], isError: true };
    }
    const products = (data ?? []).map((p) => {
      const now = Date.now();
      const inPromo = p.promo_price_cents != null && (!p.promo_starts_at || new Date(p.promo_starts_at).getTime() <= now) && (!p.promo_ends_at || new Date(p.promo_ends_at).getTime() > now);
      const cents = inPromo ? p.promo_price_cents : p.price_cents;
      const price = cents ? `$${(cents / 100).toFixed(cents % 100 === 0 ? 0 : 2)}` : "$0";
      const cadence = p.billing_type === "recurring" ? "/mo" : p.duration_days ? ` \xB7 ${p.duration_days} days` : "";
      return {
        slug: p.slug,
        name: p.name,
        description: p.description,
        price_display: `${price}${cadence}`,
        listing_id: listing_id ?? null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products, listing_id: listing_id ?? null }
    };
  }
});

// src/lib/mcp/tools/create-upgrade-checkout.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^3.25.76";
var VALID_UPGRADE_SLUGS = /* @__PURE__ */ new Set([
  "vendibook_pro",
  "boost-featured-30",
  "pro_listing_30",
  "listing_concierge"
]);
var create_upgrade_checkout_default = defineTool8({
  name: "create_upgrade_checkout",
  title: "Create an upgrade checkout link",
  description: "Return a Vendibook checkout URL for an upgrade product (Vendibook Pro, Featured Boost, Listing Concierge). The user completes payment on the secure PayPal checkout page. Does not charge the payment method directly.",
  inputSchema: {
    product_slug: z8.enum(["vendibook_pro", "boost-featured-30", "pro_listing_30", "listing_concierge"]).describe("The upgrade product to purchase."),
    listing_id: z8.string().uuid().optional().describe("Optional listing UUID to attach the upgrade to (required for featured boost)."),
    discount_code: z8.string().optional().describe("Optional promo/discount code.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ product_slug, listing_id, discount_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    if (!VALID_UPGRADE_SLUGS.has(product_slug)) {
      return { content: [{ type: "text", text: "Unknown upgrade product." }], isError: true };
    }
    const LISTING_SCOPED = /* @__PURE__ */ new Set(["boost-featured-30", "pro_listing_30"]);
    if (LISTING_SCOPED.has(product_slug)) {
      if (!listing_id) {
        return {
          content: [{ type: "text", text: "That upgrade applies to a specific listing \u2014 provide the listing_id first." }],
          isError: true
        };
      }
      const { data: owned, error: ownErr } = await supabase.from("listings").select("id").eq("id", listing_id).eq("host_id", ctx.getUserId() ?? "").maybeSingle();
      if (ownErr) {
        return { content: [{ type: "text", text: `Listing lookup failed: ${ownErr.message}` }], isError: true };
      }
      if (!owned) {
        return { content: [{ type: "text", text: "That listing was not found on this account." }], isError: true };
      }
    }
    const { data: product, error } = await supabase.from("monetization_products").select("billing_type, is_active").eq("slug", product_slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Catalog lookup failed: ${error.message}` }], isError: true };
    }
    if (!product?.is_active) {
      return { content: [{ type: "text", text: "That upgrade is not currently available." }], isError: true };
    }
    if (product.billing_type === "recurring") {
      const { data, error: fnError } = await supabase.functions.invoke("paypal-subscription-create", {
        body: {
          product_slug,
          billing_interval: /annual|yearly/i.test(product_slug) ? "annual" : "monthly",
          return_path: listing_id ? `/listing/${listing_id}` : "/account",
          cancel_path: listing_id ? `/listing/${listing_id}` : "/pricing"
        }
      });
      if (fnError) {
        return { content: [{ type: "text", text: `Checkout failed: ${fnError.message}` }], isError: true };
      }
      const payload = data;
      const url2 = payload?.approve_url ?? payload?.url;
      if (!url2) {
        return { content: [{ type: "text", text: payload?.message ?? payload?.error ?? "We could not start that checkout." }], isError: true };
      }
      return {
        content: [{ type: "text", text: `Complete payment here: ${url2}` }],
        structuredContent: { product_slug, listing_id: listing_id ?? null, checkout_url: url2 }
      };
    }
    const params = new URLSearchParams();
    if (listing_id) params.set("listing_id", listing_id);
    params.set("success", listing_id ? `/listing/${listing_id}` : "/account");
    params.set("cancel", listing_id ? `/listing/${listing_id}` : "/pricing");
    if (discount_code) params.set("discount", discount_code);
    const qs = params.toString();
    const url = `/checkout/product/${product_slug}${qs ? `?${qs}` : ""}`;
    return {
      content: [{ type: "text", text: `Complete payment on the secure checkout page: ${url}` }],
      structuredContent: { product_slug, listing_id: listing_id ?? null, checkout_url: url }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nbrehbwfsmedbelzntqs";
var mcp_default = defineMcp({
  name: "vendibook-mcp",
  title: "Vendibook",
  version: "0.1.0",
  instructions: "Tools for Vendibook \u2014 the marketplace for food trucks, trailers, shared kitchens, and vendor lots. Public tools: `search_listings`, `get_listing`. Authenticated tools: `list_my_listings`, `list_my_bookings`, `check_listing_blockers`, `publish_listing`, `list_upsell_products`, `create_upgrade_checkout`. Use `check_listing_blockers` before publishing. Use `list_upsell_products` and `create_upgrade_checkout` for Vendibook Pro, Featured Boost, and Listing Concierge upgrades.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_listings_default,
    get_listing_default,
    list_my_listings_default,
    list_my_bookings_default,
    check_listing_blockers_default,
    publish_listing_default,
    list_upsell_products_default,
    create_upgrade_checkout_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
