// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-listings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var SUPABASE_URL = process.env.SUPABASE_URL;
var SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search Vendibook listings",
  description: "Search published Vendibook marketplace listings (food trucks, trailers, shared kitchens, vendor lots) by keyword, city, or transaction type. Returns public listing summaries only.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search across title and description."),
    city: z.string().optional().describe("Filter by city name."),
    transaction_type: z.enum(["rent", "sale", "any"]).optional().describe("Filter by rent, sale, or any."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, transaction_type, limit }) => {
    const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("listings").select("id,title,city,state,price,transaction_type,category,published_at").eq("status", "published").not("published_at", "is", null).is("deleted_at", null).eq("moderation_status", "clear").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (query) q = q.ilike("title", `%${query}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    if (transaction_type && transaction_type !== "any") {
      q = q.eq("transaction_type", transaction_type);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SUPABASE_URL2 = process.env.SUPABASE_URL;
var SUPABASE_KEY2 = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "Get a Vendibook listing",
  description: "Fetch the full public detail for a single published Vendibook listing by id.",
  inputSchema: {
    listing_id: z2.string().uuid().describe("The listing UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ listing_id }) => {
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_KEY2, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("listings").select("*").eq("id", listing_id).eq("status", "published").not("published_at", "is", null).is("deleted_at", null).eq("moderation_status", "clear").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Listing not found or not published." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { listing: data }
    };
  }
});

// src/lib/mcp/tools/list-my-listings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SUPABASE_URL3 = process.env.SUPABASE_URL;
var SUPABASE_KEY3 = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
function supabaseForUser(ctx) {
  return createClient3(SUPABASE_URL3, SUPABASE_KEY3, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_listings_default = defineTool3({
  name: "list_my_listings",
  title: "List my Vendibook listings",
  description: "List all listings owned by the signed-in Vendibook user (drafts, published, and archived).",
  inputSchema: {
    status: z3.enum(["draft", "published", "archived", "any"]).optional().describe("Filter by status, default any."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    let q = supabaseForUser(ctx).from("listings").select("id,title,status,transaction_type,city,state,price,published_at,updated_at").eq("owner_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status && status !== "any") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var SUPABASE_URL4 = process.env.SUPABASE_URL;
var SUPABASE_KEY4 = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
function supabaseForUser2(ctx) {
  return createClient4(SUPABASE_URL4, SUPABASE_KEY4, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_bookings_default = defineTool4({
  name: "list_my_bookings",
  title: "List my Vendibook bookings",
  description: "List bookings made by the signed-in Vendibook user, most recent first. Respects Vendibook's per-user access rules.",
  inputSchema: {
    role: z4.enum(["shopper", "host", "any"]).optional().describe("Filter by whether you are the shopper (renter/buyer) or the host. Default any."),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ role, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const uid = ctx.getUserId();
    let q = supabaseForUser2(ctx).from("bookings").select(
      "id,listing_id,status,payment_status,start_date,end_date,total_amount,shopper_id,host_id,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (role === "shopper") q = q.eq("shopper_id", uid);
    else if (role === "host") q = q.eq("host_id", uid);
    else q = q.or(`shopper_id.eq.${uid},host_id.eq.${uid}`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nbrehbwfsmedbelzntqs";
var mcp_default = defineMcp({
  name: "vendibook-mcp",
  title: "Vendibook",
  version: "0.1.0",
  instructions: "Tools for Vendibook \u2014 the marketplace for food trucks, trailers, shared kitchens, and vendor lots. Use `search_listings` and `get_listing` for public marketplace data. Use `list_my_listings` and `list_my_bookings` to act as the signed-in user. All per-user tools respect Vendibook's ownership and privacy rules.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_listings_default, get_listing_default, list_my_listings_default, list_my_bookings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
